on-focused-monitor-changed = [ 'move-mouse monitor-lazy-center' ]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 50

start-at-login = true

[gaps]
inner.horizontal = 16
inner.vertical = 16
outer.left = 72
outer.bottom = 72
outer.top = 112
outer.right = 72


[mode.main.binding] 
alt-space = [ 'mode term', 'workspace T' ]

cmd-alt-q = [ 'mode main', 'workspace 1' ]
cmd-alt-w = [ 'mode main', 'workspace 2' ]
cmd-alt-e = [ 'mode main', 'workspace 3' ]
cmd-alt-r = [ 'mode main', 'workspace 4' ]
cmd-alt-u = [ 'mode main', 'workspace 5' ]
cmd-alt-i = [ 'mode main', 'workspace 6' ]
cmd-alt-o = [ 'mode main', 'workspace 7' ]
cmd-alt-p = [ 'mode main', 'workspace 8' ]

alt-shift-q = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-w = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-e = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-r = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-u = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-i = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-o = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-p = 'move-node-to-workspace 8 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = [
  'move-workspace-to-monitor --wrap-around next',
  'exec-and-forget $triggerWorkspaceMonitorChange'
]

alt-shift-semicolon = 'mode service'


[mode.term.binding] 
alt-space = [ 'mode main', 'workspace-back-and-forth' ]

cmd-alt-q = [ 'mode main', 'workspace 1' ]
cmd-alt-w = [ 'mode main', 'workspace 2' ]
cmd-alt-e = [ 'mode main', 'workspace 3' ]
cmd-alt-r = [ 'mode main', 'workspace 4' ]
cmd-alt-u = [ 'mode main', 'workspace 5' ]
cmd-alt-i = [ 'mode main', 'workspace 6' ]
cmd-alt-o = [ 'mode main', 'workspace 7' ]
cmd-alt-p = [ 'mode main', 'workspace 8' ]

alt-shift-q = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-w = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-e = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-r = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-u = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-i = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-o = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-p = 'move-node-to-workspace 8 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = [
  'move-workspace-to-monitor --wrap-around next',
  'exec-and-forget $triggerWorkspaceMonitorChange'
]

alt-shift-semicolon = 'mode service'


[mode.service.binding]
esc = [ 'reload-config', 'mode main' ]
r = [ 'flatten-workspace-tree', 'mode main' ]
f = [ 'layout floating tiling', 'mode main' ]
backspace = [ 'close-all-windows-but-current', 'mode main' ]


[workspace-to-monitor-force-assignment]
T = 'main'

# Home
1 = 'main'

# Zoom
4 = 'main'

# Notes
5 = [
  'secondary',
  'main'
]

# Unused
6 = [
  'secondary',
  'main'
]

# Unused
7 = [
  'secondary',
  'main'
]

# Mail
8 = [
  'secondary',
  'main'
]


# Kitty
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = [ 'move-node-to-workspace T --focus-follows-window' ]

# Finder
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = [ 'layout floating', 'move-node-to-workspace 1' ]

# Zen
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = [ 'move-node-to-workspace 2 --focus-follows-window' ]

# Chrome
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.during-aerospace-startup = true
run = [ 'move-node-to-workspace 2 --focus-follows-window' ]

# Discord
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = [ 'move-node-to-workspace 3' ]

# Slack
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = [ 'move-node-to-workspace 3' ]

# Zoom
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = [ 'move-node-to-workspace 4 --focus-follows-window' ]

# Obsidian
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = [ 'move-node-to-workspace 5' ]

# TickTick
[[on-window-detected]]
if.app-id = 'com.TickTick.task.mac'
run = [ 'move-node-to-workspace 6 --focus-follows-window' ]

# Notion Calendar
[[on-window-detected]]
if.app-id = 'com.cron.electron'
run = [ 'move-node-to-workspace 7' ]

# Mail
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = [ 'move-node-to-workspace 8' ]

# Proton Mail
[[on-window-detected]]
if.app-id = 'ch.protonmail.desktop'
run = [ 'move-node-to-workspace 8' ]

