"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[nodejs]
disabled = true

[ruby]
disabled = true

[git_status]
disabled = true

[package]
disabled = true

[pulumi]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

