version: '3'

vars:
  GO_SOURCES: '{apps,examples,app,config,util}/**/*.go'
  MAIN: examples/eleonora/main.go

tasks:
  build:
    sources:
      - "{{.GO_SOURCES}}"
      - shizuku.go
    generates:
      - out/shizuku
    cmds:
      - go build -o out/shizuku {{.MAIN}}
  configmax:
    watch: true
    sources:
      - "apps/**/*"
    cmds:
      - go run {{.MAIN}} sync
  run:
    cmds:
      - go run {{.MAIN}} {{.CLI_ARGS}}
  lint:
    sources:
      - "{{.GO_SOURCES}}"
    cmds:
      - go fmt ./...
  test:
    sources:
      - "{{.GO_SOURCES}}"
    cmds:
      - go test {{.CLI_ARGS}} ./...
  install:
    deps:
      - build
    cmds:
      - cp out/shizuku "$(go env GOPATH)/bin/"
