package themes

import "github.com/eleonorayaya/shizuku/styles"

var MonadeDark = styles.Theme{
	Name: "monade-dark",
	Type: "dark",
	Colors: styles.ThemeColors{
		Surface:               "#2a2520",
		SurfaceVariant:        "#332e28",
		SurfaceHighlight:      "#3d2c2a",
		SurfaceBorder:         "#4a3830",
		TextOnSurface:         "#e8dfd5",
		TextOnSurfaceVariant:  "#c4b8ac",
		TextOnSurfaceMuted:    "#8a7873",
		TextOnSurfaceEmphasis: "#fef6f0",
		Primary:               "#e6537a",
		PrimaryVariant:        "#d16577",
		TextOnPrimary:         "#fef6f0",
		Secondary:             "#d97c6e",
		TextOnSecondary:       "#2a2520",
		Tertiary:              "#9370b9",
		TertiaryVariant:       "#a87bb7",
		TextOnTertiary:        "#fef6f0",
		Accent:                "#e6537a",
		AccentPeach:           "#d97c6e",
		AccentSalmon:          "#d16577",
		AccentPurple:          "#9370b9",
		AccentLavender:        "#a87bb7",
		AccentGold:            "#b8733f",
		AccentYellow:          "#b8873f",
		AccentMint:            "#5fafa5",
		AccentBlue:            "#6a9bc3",
		Error:                 "#d16577",
		TextOnError:           "#fef6f0",
		Warning:               "#b8733f",
		TextOnWarning:         "#2a2520",
		Success:               "#9370b9",
		TextOnSuccess:         "#2a2520",
		Info:                  "#6a9bc3",
		TextOnInfo:            "#2a2520",
		Selection:             "#4a2a2a",
		SelectionForeground:   "#e8dfd5",
		Cursor:                "#e6537a",
		CursorText:            "#2a2520",
		Link:                  "#a87bb7",
		LinkHover:             "#9370b9",
		Comment:               "#8a7873",
	},
}
