package app

import (
	"fmt"
	"os"
	"path"
	"sort"
	"strings"
	"time"
)

type EnvProvider interface {
	Env() (*EnvSetup, error)
}

type EnvSetup struct {
	PreInitScripts  []string
	Variables       []EnvVar
	PathDirs        []PathDir
	InitScripts     []string
	Aliases         []Alias
	Functions       []ShellFunction
	PostInitScripts []string
}

type EnvVar struct {
	Key   string
	Value string
}

type PathDir struct {
	Path     string
	Priority int
}

type Alias struct {
	Name    string
	Command string
}

type ShellFunction struct {
	Name string
	Body string
}

func GenerateEnvFiles(envSetups []*EnvSetup, outDir string) (map[string]string, error) {
	preInitScripts := []string{}
	vars := make(map[string]string)
	pathDirs := []PathDir{}
	initScripts := []string{}
	aliases := make(map[string]string)
	functions := make(map[string]string)
	postInitScripts := []string{}

	for _, setup := range envSetups {
		preInitScripts = append(preInitScripts, setup.PreInitScripts...)
		initScripts = append(initScripts, setup.InitScripts...)
		postInitScripts = append(postInitScripts, setup.PostInitScripts...)

		for _, v := range setup.Variables {
			vars[v.Key] = v.Value
		}

		pathDirs = append(pathDirs, setup.PathDirs...)

		for _, a := range setup.Aliases {
			aliases[a.Name] = a.Command
		}

		for _, f := range setup.Functions {
			functions[f.Name] = f.Body
		}
	}

	sort.Slice(pathDirs, func(i, j int) bool {
		return pathDirs[i].Priority < pathDirs[j].Priority
	})

	timestamp := time.Now().Format("2006-01-02 15:04:05")

	var zshenv strings.Builder
	zshenv.WriteString("#!/usr/bin/env zsh\n")
	zshenv.WriteString("# Auto-generated by shizuku - DO NOT EDIT MANUALLY\n")
	zshenv.WriteString(fmt.Sprintf("# Generated at: %s\n", timestamp))
	zshenv.WriteString("# Source from .zshenv: source ~/.config/shizuku/shizuku.zshenv\n")
	zshenv.WriteString("\n")

	if len(vars) > 0 {
		zshenv.WriteString("# ============================================================\n")
		zshenv.WriteString("# Environment Variables\n")
		zshenv.WriteString("# ============================================================\n")

		sortedVarKeys := make([]string, 0, len(vars))
		for k := range vars {
			sortedVarKeys = append(sortedVarKeys, k)
		}
		sort.Strings(sortedVarKeys)

		for _, k := range sortedVarKeys {
			zshenv.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, vars[k]))
		}
		zshenv.WriteString("\n")
	}

	if len(pathDirs) > 0 {
		zshenv.WriteString("# ============================================================\n")
		zshenv.WriteString("# PATH Configuration\n")
		zshenv.WriteString("# ============================================================\n")

		pathParts := []string{}
		for _, pd := range pathDirs {
			pathParts = append(pathParts, pd.Path)
		}
		pathParts = append(pathParts, "$PATH")

		zshenv.WriteString(fmt.Sprintf("export PATH=\"%s\"\n", strings.Join(pathParts, ":")))
		zshenv.WriteString("\n")
	}

	var sh strings.Builder
	sh.WriteString("#!/usr/bin/env zsh\n")
	sh.WriteString("# Auto-generated by shizuku - DO NOT EDIT MANUALLY\n")
	sh.WriteString(fmt.Sprintf("# Generated at: %s\n", timestamp))
	sh.WriteString("# Source from .zshrc: source ~/.config/shizuku/shizuku.sh\n")
	sh.WriteString("\n")

	if len(preInitScripts) > 0 {
		sh.WriteString("# ============================================================\n")
		sh.WriteString("# Pre-Initialization Scripts\n")
		sh.WriteString("# ============================================================\n")
		for _, script := range preInitScripts {
			sh.WriteString(script)
			sh.WriteString("\n\n")
		}
	}

	if len(initScripts) > 0 {
		sh.WriteString("# ============================================================\n")
		sh.WriteString("# Initialization Scripts\n")
		sh.WriteString("# ============================================================\n")
		for _, script := range initScripts {
			sh.WriteString(script)
			sh.WriteString("\n\n")
		}
	}

	if len(aliases) > 0 {
		sh.WriteString("# ============================================================\n")
		sh.WriteString("# Aliases\n")
		sh.WriteString("# ============================================================\n")

		sortedAliasKeys := make([]string, 0, len(aliases))
		for k := range aliases {
			sortedAliasKeys = append(sortedAliasKeys, k)
		}
		sort.Strings(sortedAliasKeys)

		for _, k := range sortedAliasKeys {
			sh.WriteString(fmt.Sprintf("alias %s='%s'\n", k, aliases[k]))
		}
		sh.WriteString("\n")
	}

	if len(functions) > 0 {
		sh.WriteString("# ============================================================\n")
		sh.WriteString("# Shell Functions\n")
		sh.WriteString("# ============================================================\n")

		sortedFuncKeys := make([]string, 0, len(functions))
		for k := range functions {
			sortedFuncKeys = append(sortedFuncKeys, k)
		}
		sort.Strings(sortedFuncKeys)

		for _, k := range sortedFuncKeys {
			sh.WriteString(fmt.Sprintf("function %s() {\n%s\n}\n\n", k, functions[k]))
		}
	}

	if len(postInitScripts) > 0 {
		sh.WriteString("# ============================================================\n")
		sh.WriteString("# Post-Initialization Scripts\n")
		sh.WriteString("# ============================================================\n")
		for _, script := range postInitScripts {
			sh.WriteString(script)
			sh.WriteString("\n")
		}
	}

	fileMap := make(map[string]string)

	zshenvPath := path.Join(outDir, "shizuku.zshenv")
	if err := os.WriteFile(zshenvPath, []byte(zshenv.String()), 0644); err != nil {
		return nil, fmt.Errorf("failed to write zshenv file: %w", err)
	}
	fileMap["shizuku.zshenv"] = zshenvPath

	shPath := path.Join(outDir, "shizuku.sh")
	if err := os.WriteFile(shPath, []byte(sh.String()), 0644); err != nil {
		return nil, fmt.Errorf("failed to write sh file: %w", err)
	}
	fileMap["shizuku.sh"] = shPath

	return fileMap, nil
}
