version: '3'

tasks:
  build:
    sources:
      - '**/*.go'
    cmds:
      - go build -o out/shizuku cmd/main.go
  dev:
    deps:
      - build
    watch: true
    cmds:
      - ./out/main daemon
  fmt:
    sources:
      - '**/*.go'
    cmds:
      - go fmt ./...

