version: '3'

vars:
  GO_SOURCES: '{apps,cmd,internal}/**/*.go'

tasks:
  build:
    sources:
      - "{{.GO_SOURCES}}"
    cmds:
      - go build -o out/shizuku cmd/main.go
  run:
    cmds:
      - go run cmd/main.go {{.CLI_ARGS}}
  fmt:
    sources:
      - "{{.GO_SOURCES}}"
    cmds:
      - go fmt ./...
  test:
    sources:
      - "{{.GO_SOURCES}}"
    cmds:
      - go test {{.CLI_ARGS}} ./...

