package shizukuenv

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

func GenerateEnvFile(envSetups []*EnvSetup, outPath string) error {
	initScripts := []string{}
	vars := make(map[string]string)
	pathDirs := []PathDir{}
	aliases := make(map[string]string)
	functions := make(map[string]string)

	for _, setup := range envSetups {
		initScripts = append(initScripts, setup.InitScripts...)

		for _, v := range setup.Variables {
			vars[v.Key] = v.Value
		}

		pathDirs = append(pathDirs, setup.PathDirs...)

		for _, a := range setup.Aliases {
			aliases[a.Name] = a.Command
		}

		for _, f := range setup.Functions {
			functions[f.Name] = f.Body
		}
	}

	sort.Slice(pathDirs, func(i, j int) bool {
		return pathDirs[i].Priority < pathDirs[j].Priority
	})

	var sb strings.Builder

	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Auto-generated by shizuku - DO NOT EDIT MANUALLY\n")
	sb.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("# Source this file from your .zshrc:\n")
	sb.WriteString("#   source ~/.config/shizuku/shizuku.sh\n")
	sb.WriteString("\n")

	if len(vars) > 0 {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# Environment Variables\n")
		sb.WriteString("# ============================================================\n")

		sortedVarKeys := make([]string, 0, len(vars))
		for k := range vars {
			sortedVarKeys = append(sortedVarKeys, k)
		}
		sort.Strings(sortedVarKeys)

		for _, k := range sortedVarKeys {
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, vars[k]))
		}
		sb.WriteString("\n")
	}

	if len(pathDirs) > 0 {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# PATH Configuration\n")
		sb.WriteString("# ============================================================\n")

		pathParts := []string{}
		for _, pd := range pathDirs {
			pathParts = append(pathParts, pd.Path)
		}
		pathParts = append(pathParts, "$PATH")

		sb.WriteString(fmt.Sprintf("export PATH=\"%s\"\n", strings.Join(pathParts, ":")))
		sb.WriteString("\n")
	}

	if len(initScripts) > 0 {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# Initialization Scripts\n")
		sb.WriteString("# ============================================================\n")
		for _, script := range initScripts {
			sb.WriteString(script)
			sb.WriteString("\n\n")
		}
	}

	if len(aliases) > 0 {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# Aliases\n")
		sb.WriteString("# ============================================================\n")

		sortedAliasKeys := make([]string, 0, len(aliases))
		for k := range aliases {
			sortedAliasKeys = append(sortedAliasKeys, k)
		}
		sort.Strings(sortedAliasKeys)

		for _, k := range sortedAliasKeys {
			sb.WriteString(fmt.Sprintf("alias %s='%s'\n", k, aliases[k]))
		}
		sb.WriteString("\n")
	}

	if len(functions) > 0 {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# Shell Functions\n")
		sb.WriteString("# ============================================================\n")

		sortedFuncKeys := make([]string, 0, len(functions))
		for k := range functions {
			sortedFuncKeys = append(sortedFuncKeys, k)
		}
		sort.Strings(sortedFuncKeys)

		for _, k := range sortedFuncKeys {
			sb.WriteString(fmt.Sprintf("function %s() {\n%s\n}\n\n", k, functions[k]))
		}
	}

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}

	return nil
}
